# -*- coding: utf-8 -*-
"""Puntaje de Cáscara Founders — cinco ejes de 0 a 4 sobre el estado del negocio,
más el ritmo, que mide cómo viene ejecutando la persona (eso no puntúa el negocio)."""
import json

EJES = [
    ("oferta",    "Oferta",    "Qué vende, a quién y a qué precio. Escrita, no en la cabeza."),
    ("contenido", "Contenido", "Volumen y criterio sostenidos, no piezas sueltas."),
    ("demanda",   "Demanda",   "Conversaciones que entran sin que salga a buscarlas."),
    ("venta",     "Venta",     "Lo que convierte esa conversación en plata: embudo, llamada, cierre, precio validado."),
    ("entrega",   "Entrega",   "Puede cumplir lo que vende sin romperse."),
]
ORIENT = {"oferta":"Conseguir","venta":"Conseguir","contenido":"Sostener",
          "demanda":"Sostener","entrega":"Entregar"}
RITMO = {"verde":"Hace lo que queda de cada llamada.",
         "amarillo":"Avanza a los tirones.",
         "rojo":"Hace tiempo que no mueve."}

# slug: (oferta, contenido, demanda, venta, entrega, ritmo, nota del eje más flojo)
# Puntuado contra los anclajes de rubrica/ANCLAJES.md: cada número con evidencia en EV.
S = {
 "agostina-marchesini": (1,1,1,1,1,"verde","Los cinco ejes empatan en uno y el que manda es oferta: sin la consultoría escrita con precio y fecha, el 10 de octubre en Kaipi no hay nada que vender."),
 "scarlett-montilla": (1,2,1,1,1,"amarillo","Se trabaja por oferta, que es el eje más bajo: hasta que la mentoría no tenga una hoja con transformación, cliente ideal y precio, la demanda y la venta no tienen de qué agarrarse."),
 "ayelen-cerqueira": (1,1,1,2,2,"amarillo","Se trabaja por oferta, el eje más bajo junto con contenido: el rol ya funciona, lo que falta es la hoja con nombre, cliente ideal y precio para poder presentar Cósmico con número."),
 "lucio-labate": (1,1,1,1,2,"rojo","Se puntúa su propia oferta de IA, que es sobre la que corre el roadmap. Cuatro habilidades empatan abajo y manda oferta: sin el documento con precio, cada pieza tiene que resolver qué decir y para qué al mismo tiempo."),
 "custom-lab": (1,0,1,3,2,"verde","Contenido está en cero y es el piso: la cuenta está parada, y sin ángulo con chispazo no hay nada que pautar. La oferta baja a uno porque los kits se están redefiniendo y el precio recién sale de la llamada con Franco."),
 "sol-boutmy": (2,1,1,2,2,"verde","Los pisos son contenido y demanda, las dos en uno: la cuenta de Be Motion no cuenta qué hacen y los seis clientes entraron por boca a boca, así que el trabajo de fondo es sostener, en paralelo a sacarse la edición de encima."),
 "andrea-saturno": (1,1,1,1,2,"amarillo","Se puntúan las Bonfire Sessions, que es lo que trabaja el roadmap; la agencia con Sophie factura y entrega, y eso queda afuera del puntaje. Cuatro empatan abajo y manda contenido: sin una pieza publicada, la fecha de la primera sesión es lo único que empieza a mover algo."),
 "jose-david-fajardo": (2,1,2,2,1,"verde","Los pisos son contenido y entrega. La oferta baja a dos porque la escalera vieja está escrita y vendida, y la nueva todavía no tiene la cifra al lado."),
 "sebastian": (1,4,2,0,2,"verde","Venta en cero es el piso: tiene tráfico, autoridad y ángulos validados, y lo que falta es un precio sobre la mesa y la primera llamada de venta con ese número."),
 "sofia-galvis": (2,0,1,3,2,"verde","Contenido está en cero y es el piso: su marca personal no comunica lo que sabe enseñar. La oferta baja a dos porque el sistema de noventa días está escrito con precio y el producto de educación, que es lo que trabaja el roadmap, todavía no existe."),
 "aaron-aiello": (1,1,1,1,2,"amarillo","Se puntúa el B2C, que es el negocio sobre el que corre el roadmap. Cuatro habilidades empatan abajo y manda contenido, porque es la que el roadmap trabaja primero: la oferta B2C se escribe con lo que conteste la audiencia, y hoy hay un video y unas historias."),
 "nicolas-lozada": (3,4,1,1,1,"rojo","Demanda, venta y entrega empatan abajo y manda venta, que es el cuello del caso y el cuello del caso: hay oferta, pilares y 41 contenidos cargados, y lo único que nunca pasó fue salir a buscar la venta, así que se arranca por recontacto y prospección."),
 "qualita": (3,1,1,2,3,"rojo","Se trabaja por contenido y demanda, los dos ejes más bajos: el método ya está probado y lo que no existe es el canal propio que lo comunique, que es la única forma de elegir mejor los leads y subir el ticket."),
 "antonio-mazzello": (3,2,1,3,2,"rojo","Se trabaja por demanda, el eje más bajo: el embudo de captación quedó en el papel desde abril y sin dueño del calendario no hay diez piezas con un mismo ángulo que traigan contactos."),
 "manu-bruzzone": (3,2,1,2,3,"rojo","Se trabaja por demanda, el eje más bajo: la campaña de captación y la base de datos son lo único que mueve la cartera de veintidós a treinta y cinco, y eso se resuelve repitiendo la cadencia mensual."),
 "lola-berutti": (2,2,3,1,2,"verde","Venta es el piso y el cuello del caso: el tráfico ya está juntado y entre la conversación y la plata no hay embudo, fecha, escasez ni seña. La oferta baja a dos porque el programa todavía no registra precio ni fecha de lanzamiento."),
 "matias-morales": (4,2,2,3,1,"amarillo","Entrega en uno es el piso: vende y vende caro, y lo que falta es escribir el proceso una sola vez y aplicarlo a las dos entregas en curso antes de que entre el tercer cliente."),
 "sharon-palacio": (4,0,1,3,4,"amarillo","Se trabaja por contenido, que es el eje más bajo y está en cero: el negocio y la entrega ya funcionan, y lo único que nunca arrancó es contar los casos de éxito que ella misma genera."),
 "lucca-sorgoni": (4,1,1,4,3,"rojo","Se puntúa el B2B, que es sobre el que corre el roadmap; el B2C que le da diez mil por mes queda afuera. Ahí la oferta y la venta están probadas y el piso son contenido y demanda: del B2B no hay una sola pieza y las cuarenta propiedades entraron todas por red y referidos."),
 "bianca-antonini": (4,4,3,2,2,"verde","Se trabaja por venta y entrega, los dos ejes más bajos: el mecanismo de lanzamiento —preventa a la comunidad, ventana corta y producto disponible cuando sale la conversión— es lo que convierte el contenido que ya funciona en ventas medibles."),
}

# La evidencia de cada número, para poder auditar el puntaje sin volver a la ficha.
EV = {
 "agostina-marchesini": {"oferta":"'No hay oferta escrita. No hay ICP, ni promesa, ni módulos, ni precio, ni fecha': sabe el rumbo, la consultoría para arquitectos, y nada más.", "contenido":"Recién 'resolvió su primer contenido y grabó el siguiente'; las dos piezas semanales son objetivo y el volumen depende de cerrar a Ibi.", "demanda":"Lo que entró fueron felicitaciones por Instagram después de la charla, de la sala y de su red; consultas de consultoría, 'hoy cero'.", "venta":"Cobra proyectos del estudio desde hace ocho años, pero de la consultoría cero ventas y las llamadas de venta están recién en el roadmap de octubre.", "entrega":"El entregable de la consultoría no existe todavía (sin módulos ni scope) y lo que sostiene hoy es el estudio con una sociedad que la frena.", "ritmo":"'Cuando sabe exactamente qué tiene que hacer, lo hace': dio la charla, subió el primer video, grabó el siguiente y contrató a Ibi."},
 "scarlett-montilla": {"oferta":"La lectura dice que lo que le falta es que la mentoría esté escrita: qué transformación deja, para quién y a qué precio; sigue en borrador en el one thing.", "contenido":"Publica y Fede le revisó el video de YouTube (160 reproducciones, 7 suscriptores), pero Juana le marcó separar las dos narrativas mezcladas y está en un embudo de ideas sin ejecutar.", "demanda":"Las personas con las que ya habló nunca vinieron de Instagram; el roadmap dice que los clientes tienen que salir de la comunidad.", "venta":"Dos propuestas caídas: la clienta de Estados Unidos no cerró y Tito eligió a otra persona que le sumaba pauta; no hay proceso, cada intento fue distinto.", "entrega":"El triángulo de la sinergia es una teoría propia que recién está documentando en el one thing, y Juana le dijo que grabe igual porque todavía no tiene mentoreados.", "ritmo":"Llegó con la decisión nombrada y estuvo en las tres grupales de septiembre y en el mapa de presencia, pero el one-sheeter sigue sin terminar y en el medio se desvió meses del objetivo con el que entró."},
 "ayelen-cerqueira": {"oferta":"La oferta no tiene una hoja: no está el nombre del rol que vende, ni a quién se le vende, ni cuánto sale.", "contenido":"El video de YouTube sobre el origen de la oferta y el carrusel de volver a presentarse siguen en el roadmap de octubre; crear contenido semanal figura como accionable pendiente.", "demanda":"Julieta Peña la derivó Facu y los discovery con Micaela y Ariel salieron de prospección propia; el único entrante espontáneo registrado es Ivo Llanes.", "venta":"Cambió el proceso y ahora cobra la llamada de discovery, y tiene dos trabajos corriendo, pero Cósmico es caso de prueba desde julio y la propuesta sigue sin presentarse con precio.", "entrega":"Ejecuta el rol de community success manager todos los días y delega operativo en Mora, pero el proceso no está documentado (queda para noviembre) y el rol crece más rápido de lo que ella lo escribe.", "ritmo":"Prospecta, tomó dos clientes nuevos y sostiene el rol adentro, pero la reunión con Franco quedó pendiente del 1 de septiembre y la definición de la oferta se viene corriendo desde julio."},
 "lucio-labate": {"oferta":"La lectura dice que no hay un documento que diga qué vende, a quién y a cuánto; la oferta está trabajada pero no cerrada y falta ponerle precio con Franco.", "contenido":"Facu se lo dijo así: de los quince videos que tenía que subir, subió uno, y además el contenido apunta al diseñador genérico y no al dolor del buyer.", "demanda":"Facu le marcó que lo que sube le gusta, tiene buenas repercusiones y abre conversaciones, pero con un video publicado eso se apaga si deja de publicar.", "venta":"Facu le dijo que no puede concluir que no le sale vender si nunca lo probó; cero llamadas de venta hechas, cobra por trabajos sueltos del tipo si le piden una landing la hace.", "entrega":"Entrega IA adentro de Wellmate todos los días, con deepfakes, guiones y contenido, y resuelve solo lo que antes necesitaba tres personas: entrega bien y todo pasa por él.", "ritmo":"Subió uno de los quince videos comprometidos, el perfil sigue sin ordenar y Facu le dijo en la cara que está frisado porque le resulta más cómodo que transitar el cambio."},
 "custom-lab": {"oferta":"El giro está definido, publicidad hecha con merch para empresas de treinta a cincuenta empleados, startups y oficinas, pero los kits se están redefiniendo y el precio recién sale de la llamada pendiente con Franco.", "contenido":"La cuenta de Instagram está bastante muerta hace tiempo y el algoritmo hay que entrenarlo de nuevo; en la grupal del 4 les quedó arrancar al día siguiente con las primeras piezas.", "demanda":"Todo lo que venden hoy sale de que ellos salgan a empujar uno por uno, sobre conocidos del nicho cristiano; no hay e-commerce, la landing no convierte y nunca pautaron.", "venta":"Juan armó la base histórica de dos años en Notion con quién decide la compra y si repitió, salieron a recontactar y vendieron: Teo lo confirmó en el repaso y es el único motor probado.", "entrega":"Tienen buena capacidad de producción y resuelven, pero todo pasa por los dos socios y les quedó pendiente definir entre ellos los roles y los horarios fijos de producción.", "ritmo":"Ejecutaron completos los accionables que les dejó Franco (base histórica en Notion, recontacto que vendió y kits en camino) y vienen sosteniendo las llamadas: grupales del 2 y del 4 y la de procesos del 10 de septiembre."},
 "sol-boutmy": {"oferta":"Cobran mensual y contra entrega, 600 a 700 dólares de promedio, 'alguno de mil y alguno menos', sin paquete cerrado: el nicho y el precio nuevo recién salen de la auditoría con Franco.", "contenido":"'El Instagram de Be Motion no funciona como funnel': tienen redes pero no ejecutan nunca por falta de tiempo, y Facu entró y no le quedó claro qué hacen.", "demanda":"'Los clientes llegan casi todos por boca a boca, porque el mercado uruguayo es chico y se conocen todos.'", "venta":"Seis clientes fijos facturados y cobrados en fecha, pero cada propuesta y cada precio se armó a ojo: 'presupuestando como les parecía, sin nadie con quien comparar números'.", "entrega":"Entregan seis cuentas fijas con equipo de cuatro, pero 'las dos arman propuestas, las dos van a producir, las dos editan' y los calendarios están sueltos en Drive.", "ritmo":"Llegaron a la 1:1 con el documento de qué resuelve cada socia en cada cliente ya escrito a mano antes de la llamada."},
 "andrea-saturno": {"oferta":"La agencia con Sophie factura y entrega, pero las Bonfire Sessions —el objetivo con el que entró— no tienen ni la hoja de qué son, para quién y cada cuánto.", "contenido":"El vlog documental quedó definido el 28/8 con el compromiso de grabar el sábado y publicar el lunes, y todavía no salió.", "demanda":"Entró y opera por la red de F3 y el vínculo comercial de Franco; el pipeline de siete campos está armado, pero los leads propios son futuros.", "venta":"Cobra trabajo de clientes y el 10/9 centralizó el pipeline del lead a la venta en un solo Notion, pero no hay registro de una venta cerrada con ese proceso.", "entrega":"La agencia entrega y las operaciones quedaron documentadas con Teo, pero ella está metida en producción y por eso el formato propio quedó atrás de los clientes.", "ritmo":"Sostuvo las sesiones de procesos hasta el 10/9, pero Facu sigue esperando la fecha de las Bonfire Sessions y la pieza comprometida para el lunes nunca salió."},
 "jose-david-fajardo": {"oferta":"Tiene la escalera escrita con precios (100 / 500 / 3.000 / 4.500) y cliente ideal identificado, y 'las tres ventas anteriores de tres mil dólares' son de esa escalera vieja, previas a la Clarity Call; de la oferta nueva 'no hay todavía un documento que diga qué promete, cómo lo mide y a cuánto lo vende', así que no llega a 4.", "contenido":"Lo único hecho es el ajuste de perfil: los ángulos salen de una oferta que todavía no está cerrada y las diez piezas contra esos ángulos están pendientes.", "demanda":"'Modificó un par de cosas del perfil y por esos dos cambios le llegaron cinco consultas', pero 'llegan de rebote del perfil, no de un sistema que las traiga'.", "venta":"Cobró tres ventas de 3.000 dólares con la escalera vieja, pero 'la venta depende de lo bien que salga cada charla' y los leads llegan sin calificar; de la oferta nueva, cero ventas.", "entrega":"'Una entrega con procesos flojos que le daba inseguridad al momento de vender', y sistematizarla recién se decide para el tramo siguiente.", "ritmo":"'Hizo el onboarding con Teo, completó los Founder Insights y recién después fue a la Clarity Call', aplicó el profile funnel sin discutirlo y sostiene las tres grupales."},
 "sebastian": {"oferta":"'La oferta todavía no está escrita': la forma del nivel uno quedó definida el 4 de septiembre y el precio es hipótesis, mil a mil quinientos; 'lo que todavía no existe es el documento'.", "contenido":"Un reel orgánico hizo un millón cuatrocientas mil vistas, mil ochocientos comentarios y unos siete mil seguidores, y otros dos ángulos de la misma familia también funcionaron: los validó la audiencia, no el criterio propio.", "demanda":"El reel 'le abrió demanda directa' de servicios, pero 'el viral de mil ochocientos comentarios no dejó una sola conversación abierta': sin captura, se apaga.", "venta":"'El cuello es que nunca cobró': la mentoría de cinco sesiones la dio gratis a cuatro personas y 'nunca puso un precio'.", "entrega":"Dictó la mentoría de cinco sesiones y quedó grabada, y la producción la hacen él y Titi, pero falta definir qué va grabado y qué en vivo: hoy todo pasa por él.", "ritmo":"Arrancó el 1 de septiembre, hizo onboarding y Clarity Call en la misma semana y salió con tres deberes anotados; no hay nada registrado como pasado de fecha."},
 "sofia-galvis": {"oferta":"Sistema de 90 días escrito, con avatar y con el precio rearmado el 5/9 (lista 4.000, 3.500 por adelantado), pero a ese precio todavía no vendió y el programa de educación no tiene oferta escrita, ICP, precio ni fecha.", "contenido":"Lo dijo ella el 5/9: «mi marca personal está vuelta a nada», y el roadmap recién la prende en la semana del 29 de septiembre.", "demanda":"Los dos clientes nuevos entraron por sus clases en el high ticket de Sara Linares, audiencia ajena; canal propio no hay, porque su cuenta no comunica nada.", "venta":"Depuró la cartera, reprecio al cliente de edición y entraron cuatro clientes al sistema de 90 días: pasó de 10 a 20 millones de pesos colombianos por mes.", "entrega":"El sistema está estandarizado pero ella está adentro de cada cuenta: frenó la entrada de clientes nuevos por falta de lugar y el editor que contrató todavía no recibió su primer cliente.", "ritmo":"Volvió del parate de Colombia con la lista entera hecha: depuración, reprecio, sistema estandarizado con varas de éxito y editor contratado."},
 "aaron-aiello": {"oferta":"De la Clarity Call salen el avatar (el que tiene profesión y marca y no llega a cinco o diez mil por mes) y la forma que imagina para el B2C, y nada de eso está escrito ni subido al Notion, ni tiene precio. La consultoría B2B que ya vende es otro negocio y no puntúa acá.",
  "contenido":"El cierre lo dice: hoy hay un video de YouTube y unas historias; la marca personal no arranca y el perfeccionismo es la traba concreta.",
  "demanda":"Los clientes le llegaron del programa de Víctor, donde la gente se fue detrás de él cuando el trabajo terminó, y de la audiencia solo hay doscientos o trescientos activos.",
  "venta":"Cobra y cierra en el B2B con una consultoría de noventa días que repite. Del B2C nunca vendió nada: no hay precio, ni llamada de venta, ni oferta que presentar.",
  "entrega":"Sabe entregar: fue mentor de treinta o cuarenta personas por semana durante un año y medio y hoy la consultoría corre con Cami en operaciones y métricas. Para el B2C el modelo está sin resolver, que es cómo sostener la cercanía cuando la entrega deja de ser uno a uno.",
  "ritmo":"Hizo el video de YouTube que le bajó Fede y tuvo la llamada con Franco del 11 de septiembre, pero el ICP y la oferta siguen sin subir al Notion desde que se lo pidieron el 1 de septiembre."},
 "nicolas-lozada": {"oferta":"'Cinco cupos, ticket de mil dólares, acompañamiento real', con cliente ideal y alcance definidos, pero al 2 de septiembre ventas de esa oferta: ninguna.", "contenido":"'Dos piezas triplicaron o cuadruplicaron sus números' —los diez días encerrado en la oficina y subir los precios es un error— y de ahí salió el criterio, experiencia vivida y no teoría; ya publica solo y con los tres pilares definidos de antemano.", "demanda":"'Sus dos únicos clientes llegaron por referido, no por contenido' y hoy 'no hay conversaciones abiertas'.", "venta":"Cobró a dos clientes que llegaron por referido, pero 'nunca se salió a vender': sin llamadas agendadas y con 'el Calendly, los leads viejos que no cerraron y el pipeline que ya existe sin tocar'.", "entrega":"No hay proceso de entrega en la ficha: el acompañamiento lo sostiene él a pulmón, con su experiencia de trafficker, sobre dos clientes.", "ritmo":"Tres meses de proceso con el sistema entero armado y el pipeline intacto; el cierre es sign-off y no renovación justamente por eso."},
 "qualita": {"oferta":"Método propio y probado, con clientes que pagan y avatar claro, pero el pricing se definió el 22 de abril y nunca se revalidó, y lo que Rafa pide es justamente poder subir el ticket.", "contenido":"Rafa lo dijo textual: «comunicaría el método, porque nunca lo comunicamos»; hay piezas, pero ningún criterio que las una hacia el dueño de marca.", "demanda":"Los leads entran por el network, que hoy hace de filtro de entrada, y el canal propio de venta del método todavía no está formado: el funnel de Instagram a YouTube con casos y VSL nunca lo armaron.", "venta":"El embudo de abril llegó a 1500 en base, 1200 en WhatsApp, 115 de pico en la llamada del 26/4 y 9 aplicaciones, y cerró cero ventas.", "entrega":"Método propio y probado y entregan bien, pero una semana sin Ani «hace un kilombo» y la ejecución de lo acordado no llegó.", "ritmo":"Un mes de silencio entre junio y julio, el pricing del 22 de abril nunca revalidado y el funnel que pidieron todavía sin armar."},
 "antonio-mazzello": {"oferta":"El cliente quedó definido desde la primera llamada, alguien con más de cincuenta mil dólares para invertir que busca atención personalizada, y nunca se discutió; la agenda de clientes está cargada.", "contenido":"Publica: el proyecto se pinchó y se puso a crear contenido de lo que tenía ganas, y sin un ángulo único sostenido no hay nada que leer.", "demanda":"La captación de leads quedó en el papel desde abril: el mecanismo para capturar contactos desde los recortes y la planilla donde anotarlos siguen siendo punto B.", "venta":"Tiene agenda de clientes andando y la instrucción fue traer tráfico calificado y no masivo justamente para no desbordar la capacidad comercial de la firma.", "entrega":"Entrega atención personalizada, pero su agenda de clientes hace imposible que él maneje la producción y el estratega creativo que tenía que sostenerla nunca apareció.", "ritmo":"Facu le mandó un resumen completo y el hilo quedó sin respuesta en agosto, y desde abril no consiguió al estratega creativo del que dependía todo el plan."},
 "manu-bruzzone": {"oferta":"Marca personal premium de ticket alto con derivación de lo que no da a Team Bruzzone, sobre el perfil de cliente ideal que armó Franco: quedó definido en abril y no se movió.", "contenido":"Hay criterio escrito (hablar de problemas del cliente y no de recorridos de propiedades), pero la producción del equipo es despareja, sale cuando sale y no se mide.", "demanda":"Las trece propiedades que faltan tienen que salir de la campaña de captación y no de esperar referidos, y si la base de datos y las automatizaciones se implementaron falta confirmar.", "venta":"La llamada de precalificación obligatoria quedó escrita en abril, pero los procesos comerciales siguen siendo artesanales y los seguimientos post venta se pierden.", "entrega":"El servicio proactivo funciona, hay equipo de agentes con Team Bruzzone recibiendo los leads que no dan ticket alto y Ramiro entró como estratega creativo para liberar a Juana.", "ritmo":"Del 12 de junio al 2 de septiembre no hubo ninguna llamada uno a uno, la planificación mensual nunca llegó a instalarse y la cartera sigue en veintidós sobre treinta y cinco."},
 "lola-berutti": {"oferta":"El programa está terminado y Workflow tiene precio y avatar («encontrar Project Managers para agencias creativas»), pero el ticket se tuvo que rearmar después de la única venta y el programa no registra precio ni fecha.", "contenido":"Salió el primer video largo y se destrabó frente a cámara en dos semanas, pero es una sola pieza y el arco narrativo de la ineficiencia sigue sin escribirse.", "demanda":"Armó desde LinkedIn un grupo de WhatsApp con ciento sesenta PMs, tres personas llegaron por Enzo y tuvo tres llamadas de gente que le escribió sola.", "venta":"Tres llamadas de venta y cero cerradas, sin embudo, fecha, escasez ni seña; la única venta de Workflow fue a pulmón y el proyecto no siguió.", "entrega":"El programa está terminado pero nunca se entregó, y la única entrega real dependió de una sola PM que no puede insertarse en proyectos de terceros y dictar el programa a la vez.", "ritmo":"Llegó a la 1:1 del 28/8 con el primer video hecho y la lista de preguntas, y pasó de no animarse a grabar a organizarse el set sola en dos semanas."},
 "matias-morales": {"oferta":"'Matías subió los precios casi al doble y las vendió igual, todas', con dos ventas cerradas, y la promesa y el modelo de campañas con fecha de inicio y de final cerrados con Juana el 23 de julio.", "contenido":"Teo resume que 'tiene ofertas validadas y contenido', pero el 4 de septiembre 'Fede fue directo porque no había grabado' y en la del 2 contó que no llegó a aplicar nada porque estuvo vendiendo y armando Notion.", "demanda":"Las ventas salieron de oportunidades que le llegaron —'es la primera vez que vende por sistema y no porque le llegó la oportunidad'— y la base de datos se arma recién en octubre.", "venta":"Cerró todas las propuestas que armó y a casi el doble del precio pensado, sin bajar, pero las propuestas las armó con Facu y todavía no hay mecánica propia de lanzamiento que pueda repetir.", "entrega":"'Llegó al punto de que vendió, pero ahora está medio en bolas': no hay onboarding, no hay roadmap para el cliente, no hay hitos ni fechas, y resuelve sobre la marcha.", "ritmo":"Avanza a los tirones: cerró un cliente e hizo un onboarding propio, pero llegó a la grupal del 2 sin aplicar nada y a la del 4 sin haber grabado."},
 "sharon-palacio": {"oferta":"Precio mínimo de setecientos dólares por mes con alcance definido —la pauta paga queda afuera— y cuatro cuentas activas pagando; la marca de tejidos pasó a retainer mensual.", "contenido":"Su contenido propio está frenado desde hace meses: abandonó el podcast, el calendario quedó a medias y sin publicar y la editora nunca recibió material.", "demanda":"Consiguió cuatro cuentas con el contenido propio apagado, así que no hay canal: no cuenta ninguno de los casos de éxito que genera y los leads como Mars llegan por red.", "venta":"Cerró cuatro cuentas sosteniendo el mínimo de setecientos con cuotas sin interés, pero la reunión de cierre de ciclo y la propuesta de continuidad por bloques de tres meses todavía son roadmap.", "entrega":"Modelo repetible y delegado —ella deja tarjetas con objetivo, formato y referencias y el cliente guiona— con cuatro cuentas a la vez y un caso con ventas orgánicas virales que le ganaron a la pauta paga.", "ritmo":"Llega con tareas hechas, como la auditoría de la marca de ropa con las métricas cargadas a mano, pero el pedido de su propio contenido viene pendiente desde hace meses."},
 "lucca-sorgoni": {"oferta":"El B2C vendido a 1.500 dólares con diez a quince alumnos activos y diez mil dólares mensuales, y el B2B cobrando el diez por ciento del bruto en cuarenta propiedades: las dos ofertas ya se vendieron a su precio.", "contenido":"Sostiene el B2C desde su marca personal, pero 'no hay contenido de B2B' y él mismo dice que 'su propio contenido le resulta aburrido y que él tampoco le pone mucha onda a la hora de grabar'.", "demanda":"El B2C trae alumnos desde su marca personal, pero el B2B es todo red y referidos ('una propia, una de la familia, amigas de la madre y referidos') y la métrica de propiedades nuevas que no vengan de un referido es 'hoy, ninguna'.", "venta":"Subió el ticket de 1.200 a 1.500 y lo sostiene con diez a quince alumnos activos vendiendo él solo, sin setter ni closer, y en el B2B al diez por ciento 'objeciones, cero'.", "entrega":"Cuarenta propiedades administradas como co-anfitrión con estrategia de precios, software que compara mes contra mes y resultado medible a los dos meses; no está delegado: 'cuando le llegan dueños de propiedades, los deriva a otros porque no los puede atender'.", "ritmo":"'Después del 2 de abril no hay llamadas uno a uno registradas', el B2B quedó intacto y Facu lo resume: 'siempre se traba y necesita acción'."},
 "bianca-antonini": {"oferta":"236 clientas recompraron y el anillo que lanzó porque su comunidad se lo venía pidiendo se vendió muy bien.", "contenido":"Los ángulos los validó la audiencia: en TikTok la llamaban la chica de los anillos, lanzó el anillo y vendió, y la muestra de campera generó demanda antes de que el producto existiera.", "demanda":"Tiene una comunidad de WhatsApp del tamaño de las 236 recompradoras, que ya creció, y la demanda aparece antes del producto; lo que falta es medir qué parte de la venta sale de ahí.", "venta":"Vende y tiene recompra, pero el mecanismo pierde ventas: el carrusel de conversión salió sin producto disponible, la ventana de comunicación se estiró semanas y la pauta cerró la última semana sin resultado.", "entrega":"Hace diseño, producción, comunicación y contenido ella sola y no le queda tiempo para lo estratégico; en este drop las prendas llegaron después de que arrancara la comunicación.", "ritmo":"Cruzó sola los datos de recompra con el tamaño de la comunidad y llegó con lo pedido a cada instancia: llamadas el 2, 5, 9, 10 y 11 de septiembre."},
}

TRAMOS = [(0,7,"Arranque"),(8,10,"En construcción"),(11,13,"Andando"),(14,20,"Listo para cerrar")]
def tramo(t):
    for a,b,n in TRAMOS:
        if a <= t <= b: return n
    return "—"

# Cuando varias habilidades empatan abajo, manda la que el roadmap trabaja primero.
MANDA = {
    "lucio-labate": "oferta",
    "custom-lab": "contenido",
    "andrea-saturno": "contenido",
    "jose-david-fajardo": "contenido",
    "sofia-galvis": "contenido",
    "lola-berutti": "venta",
    "lucca-sorgoni": "contenido",
    "aaron-aiello": "contenido",
    "nicolas-lozada": "venta",
    "agostina-marchesini": "oferta",
}

def calcular(slug):
    if slug not in S: return None
    o,c,d,v,e,ritmo,nota = S[slug]
    val = {"oferta":o,"contenido":c,"demanda":d,"venta":v,"entrega":e}
    total = o+c+d+v+e
    piso = min(val.values())
    flojos = [k for k in val if val[k]==piso]
    m = MANDA.get(slug)
    if m in flojos: flojos = [m] + [k for k in flojos if k != m]
    return {"ejes": val, "total": total, "tramo": tramo(total),
            "ritmo": ritmo, "ritmo_texto": RITMO[ritmo],
            "eje_flojo": flojos, "sugiere": sorted({ORIENT[k] for k in flojos}),
            "nota": nota}

if __name__ == "__main__":
    import glob
    n=0
    for f in sorted(glob.glob('fichas/*.json')):
        d=json.load(open(f,encoding='utf-8'))
        h=calcular(d['slug'])
        if not h: print('SIN PUNTAJE:', d['slug']); continue
        d['handicap']=h
        json.dump(d, open(f,'w',encoding='utf-8'), ensure_ascii=False, indent=2)
        coincide = d['orientacion'] in h['sugiere']
        n+=1
        print(f"{d['slug']:24} {h['total']:2}/20  {h['tramo']:18} {h['ritmo']:9} "
              f"flojo={'+'.join(h['eje_flojo']):20} sugiere={'/'.join(h['sugiere']):20} "
              f"asignada={d['orientacion']:10} {'ok' if coincide else '← no coincide'}")
    print("fichas con puntaje:", n)
